/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "assets/**",
    "entrypoints/**/*.{ts,tsx,html}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        jet: "hsl(var(--color-jet))",
        umbra: "hsl(var(--color-umbra))",
        ink: "hsl(var(--color-ink))",
        ash: "hsl(var(--color-ash))",
        iron: "hsl(var(--color-iron))",
        steel: "hsl(var(--color-steel))",
        tin: "hsl(var(--color-tin))",
        fog: "hsl(var(--color-fog))",
        silver: "hsl(var(--color-silver))",
        pewter: "hsl(var(--color-pewter))",
        dove: "hsl(var(--color-dove))",
        nimbus: "hsl(var(--color-nimbus))",
        ivory: "hsl(var(--color-ivory))",
        midnight: "hsl(var(--color-midnight))",
        evenfall: "hsl(var(--color-evenfall))",
        breeze: "hsl(var(--color-breeze))",
        cobalt: "hsl(var(--color-cobalt))",
        gale: "hsl(var(--color-gale))",
        dawn: "hsl(var(--color-dawn))",
        sunset: "hsl(var(--color-sunset))",
        rust: "hsl(var(--color-rust))",
        dusk: "hsl(var(--color-dusk))",
        twilight: "hsl(var(--color-twilight))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          background: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
